version: '3.6'
services:
  redis-node1:
    #network_mode: host
    container_name: redis-node1
    build: #node1 #dockernode #node1
      context: ./dockernode
      dockerfile: dockerfile
      args:
        port: 7000
    #command: redis-server --port 7000
    ports: 
      - "7000:7000"
      - "17000:17000"
    # networks:
    #      extnetwork:
    #         ipv4_address: 192.168.81.5
    networks:
         extnetwork:
            ipv4_address: 172.19.0.2
  redis-node2:
    #network_mode: host
    container_name: redis-node2
    #build: node2 #dockernode #node2
    build: #node1 #dockernode #node1
      context: ./dockernode
      dockerfile: dockerfile
      args:
        port: 7001
    command: redis-server --slaveof redis-node1 7000
    #links:
    depends_on: 
      - redis-node1
    ports: 
      - "7001:7001"
      - "17001:17001"
    # networks:
    #      extnetwork:
    #         ipv4_address: 192.168.81.5
    networks:
         extnetwork:
            ipv4_address: 172.19.0.3
  redis-node3:
    #network_mode: host
    container_name: redis-node3
    #build: node3 #dockernode #node3
    build: #node1 #dockernode #node1
      context: ./dockernode
      dockerfile: dockerfile
      args:
        port: 7002
    #command: redis-server --port 7002
    ports: 
      - "7002:7002"
      - "17002:17002"
    # networks:
    #      extnetwork:
    #         ipv4_address: 192.168.81.5
    networks:
         extnetwork:
            ipv4_address: 172.19.0.4
  redis-node4:
    #network_mode: host
    container_name: redis-node4
    #build: node4 #dockernode #node4
    build: #node1 #dockernode #node1
      context: ./dockernode
      dockerfile: dockerfile
      args:
        port: 7003
    command: redis-server --slaveof redis-node3 7002
    #links:
    depends_on: 
      - redis-node3
    ports: 
      - "7003:7003"
      - "17003:17003"
    # networks:
    #      extnetwork:
    #         ipv4_address: 192.168.81.5
    networks:
         extnetwork:
            ipv4_address: 172.19.0.5
  redis-node5:
    #network_mode: host
    container_name: redis-node5
    #command: redis-server --port 7004
    #build: node5 #dockernode #node5
    build: #node1 #dockernode #node1
      context: ./dockernode
      dockerfile: dockerfile
      args:
        port: 7004
    ports: 
      - "7004:7004"
      - "17004:17004"
    # networks:
    #      extnetwork:
    #         ipv4_address: 192.168.81.5
    networks:
         extnetwork:
            ipv4_address: 172.19.0.6
  redis-node6:
    #network_mode: host
    container_name: redis-node6
    #build: node6 #dockernode #node6
    build: #node1 #dockernode #node1
      context: ./dockernode
      dockerfile: dockerfile
      args:
        port: 7005
    command: redis-server --slaveof redis-node5 7004
    #links:
    depends_on: 
      - redis-node5
    ports: 
      - "7005:7005"
      - "17005:17005"
    # networks:
    #      extnetwork:
    #         ipv4_address: 192.168.81.5
    networks:
         extnetwork:
            ipv4_address: 172.19.0.7
  redis-cluster-creator:
    #network_mode: host
    container_name: redis-cluster-creator
    #build: createnode
    image: redis:5.0.3-alpine3.9
    #command: sh -c 'echo "yes"|redis-cli -a pass.123 --cluster create ${hostip}:7000 ${hostip}:7001 ${hostip}:7002 ${hostip}:7003 ${hostip}:7004 ${hostip}:7005 --cluster-replicas 1'
    command: sh -c 'echo "yes"|redis-cli -a pass.123 --cluster create 172.19.0.2:7000 172.19.0.3:7001 172.19.0.4:7002 172.19.0.5:7003 172.19.0.6:7004 172.19.0.7:7005 --cluster-replicas 1'
    networks:
         extnetwork:
    #environment: 
    #  hostip: "192.168.81.5"
    #links:
    depends_on: 
      - redis-node1
      - redis-node2
      - redis-node3
      - redis-node4
      - redis-node5
      - redis-node6

  redis-sentinel1:
    #network_mode: host
    container_name: redis-sentinel1
    build: sentinel
    networks:
      extnetwork:
    #links:
    depends_on: 
      - redis-node1
      - redis-node2
      - redis-node3
  
  redis-sentinel2:
    #network_mode: host
    container_name: redis-sentinel2
    build: sentinel
    networks:
      extnetwork:
    #links:
    depends_on: 
      - redis-node1
      - redis-node2
      - redis-node3
  
  redis-sentinel3:
    #network_mode: host
    container_name: redis-sentinel3
    build: sentinel
    networks:
      extnetwork:
    #links:
    depends_on: 
      - redis-node1
      - redis-node2
      - redis-node3
networks:
   extnetwork:
      ipam:
         config:
         - subnet: 172.19.0.0/16 #192.168.81.0/24 #172.19.0.0/16